# Generated by Django 4.2.7 on 2025-08-05 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(db_column='log_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=100, verbose_name='table name')),
                ('record_id', models.UUIDField(blank=True, null=True, verbose_name='record ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('IMPORT', 'Import'), ('EXPORT', 'Export')], max_length=20, verbose_name='action')),
                ('old_values', models.JSONField(blank=True, default=dict, verbose_name='old values')),
                ('new_values', models.JSONField(blank=True, default=dict, verbose_name='new values')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='session ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'T_Audit_Log',
                'ordering': ['-created_at'],
            },
        ),
    ]
